name: build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout mnako/hanzi-writer-data-ja
        uses: actions/checkout@v2

      - name: Checkout parsimonhi/animCJK
        uses: actions/checkout@v2
        with:
          repository: parsimonhi/animCJK
          path: animCJK

      - name: Generate Kanji Data
        run: sh .github/workflows/build.sh

      - name: Clean
        run: rm data/.json && rm -rf animCJK
